[package]
name = "klingo"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"

[dependencies.web-sys]
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
  "EventTarget",
  "MouseEvent",
]
version = "0.3.69"
